<?php
namespace ZombieTfk\Thatcher\Tests;

require_once "../vendor/autoload.php";

use ZombieTfk\Thatcher\Pattern;

use function ZombieTfk\Thatcher\Aliases\Pattern;
use const ZombieTfk\Thatcher\Symbols\Aliases\_;

$pattern = Pattern([_],'x',7);
echo "True:";
echo ($pattern->getParsedParameters('x',7,8,9,0,1,2,3,4,5,'x',7) === [ ['x',7,8,9,0,1,2,3,4,5],'x',7 ] ? 'true' : 'false') . "\n";
echo "True:";
echo (($pattern->getParsedParameters('x',7,8,9,0,'x',7,8,9,0,'x',7) === [ ['x',7,8,9,0,'x',7,8,9,0],'x',7 ]) ? 'true' : 'false') . "\n";
echo "--------\n";
$pattern = Pattern(1,2,3);
echo "True: ";
echo (($pattern->getParsedParameters(1,2,3) === [1,2,3] ? 'true' : 'false')) . "\n";
echo "------------------\n";
$pattern = Pattern(_,2,3);
echo "True: ";
echo (($pattern->getParsedParameters(1,2,3) === [1,2,3] ? 'true' : 'false')) . "\n";
echo "True: ";
echo (($pattern->getParsedParameters(25,2,3) === [25,2,3] ? 'true' : 'false')) . "\n";
echo "------------------\n";
$pattern = Pattern(1,2,_);
echo "True: ";
echo (($pattern->getParsedParameters(1,2,3) === [1,2,3] ? 'true' : 'false')) . "\n";
echo "True: ";
echo (($pattern->getParsedParameters(1,2,25) === [1,2,25] ? 'true' : 'false')) . "\n";
echo "------------------\n";
$pattern = Pattern([_],2,3);
echo "True: ";
echo (($pattern->getParsedParameters(7,8,9,2,3) === [[7,8,9],2,3] ? 'true' : 'false')) . "\n";
echo "True: ";
echo (($pattern->getParsedParameters(7,2,3) === [[7],2,3] ? 'true' : 'false')) . "\n";
echo "True: ";
echo (($pattern->getParsedParameters(7,6,5,4,3,2,3,2,3) === [[7,6,5,4,3,2,3],2,3] ? 'true' : 'false')) . "\n";
echo "True: ";
echo (($pattern->getParsedParameters(7,6,2,5,4,3,2,3,2,3,2,3) === [[7,6,2,5,4,3,2,3,2,3],2,3] ? 'true' : 'false')) . "\n";
echo "------------------\n";
$pattern = Pattern([_],2,3,4,5);
echo "True: ";
echo (($pattern->getParsedParameters(7,8,9,2,3,2,3,4,5) === [[7,8,9,2,3],2,3,4,5] ? 'true' : 'false')) . "\n";
echo "True: ";
echo (($pattern->getParsedParameters(7,2,3) === [[7],2,3] ? 'true' : 'false')) . "\n";
echo "True: ";
echo (($pattern->getParsedParameters(7,6,5,4,3,2,3,2,3) === [[7,6,5,4,3,2,3],2,3] ? 'true' : 'false')) . "\n";
echo "True: ";
echo (($pattern->getParsedParameters(7,6,2,5,4,3,2,3,2,3,2,3) === [[7,6,2,5,4,3,2,3,2,3],2,3] ? 'true' : 'false')) . "\n";
echo "------------------\n";
$pattern = Pattern('a', 'b', [_]);
echo "True: ";
echo (($pattern->getParsedParameters('a','b','c') === ['a','b',['c']] ? 'true' : 'false')) . "\n";
echo "True: ";
echo (($pattern->getParsedParameters('a','b',1,2,3,4,5,6,7,8,9) === ['a','b',[1,2,3,4,5,6,7,8,9]] ? 'true' : 'false')) . "\n";
echo "------------------\n";
$pattern = Pattern('a', 'b', _, _, [_]);
echo "True: ";
echo (($pattern->getParsedParameters('a','b', 3, 4, 5) === ['a','b',3,4,[5]] ? 'true' : 'false')) . "\n";
echo "True: ";
echo (($pattern->getParsedParameters('a','b',1,2,3,4,5) === ['a','b',1,2,[3,4,5]] ? 'true' : 'false')) . "\n";
echo "------------------\n";
$pattern = Pattern(_,_,[_],9,0);
echo "True: ";
echo (($pattern->getParsedParameters(1,2,3,4,5,6,7,8,9,0) === [1,2,[3,4,5,6,7,8],9,0] ? 'true' : 'false')) . "\n";
$pattern = Pattern(_,_,[_],_,_);
echo "True: ";
echo (($pattern->getParsedParameters(1,2,3,4,5,6,7,8,9,0) === [1,2,[3,4,5,6,7,8],9,0] ? 'true' : 'false')) . "\n";
$pattern = Pattern([_],3,[_]);
echo "True: ";
echo (($pattern->getParsedParameters(1,2,3,4,5) === [[1,2],3,[4,5]] ? 'true' : 'false')) . "\n";
//var_dump($pattern->getParsedParameters(1,2,3,7,7,7,5,6));
echo "------------------\n";
$pattern = Pattern(1,2,[_]);
echo "True: ";
echo (($pattern->getParsedParameters(1,2,3) === [1,2,[3]] ? 'true' : 'false')) . "\n";
echo "True: ";
echo (($pattern->getParsedParameters(1,2,3,4,5,6,7,8) === [1,2,[3,4,5,6,7,8]] ? 'true' : 'false')) . "\n";
$Pattern = Pattern(_, 5);
echo "Match Last--------\n";
echo "True? : ";
echo ($Pattern->matches(1,5) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches(1,2,3,4,5) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches(3,4,5) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches(1,2,3) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches(5,3,1) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches(1,5,2) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches(5) ? 'true' : 'false') . "\n";
echo "Match First-------\n";
$Pattern = Pattern(5, _);
echo "True? : ";
echo ($Pattern->matches(5, 1) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches(5) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches(5, 1, 1) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches(5, 5, 5, 5) ? 'true' : 'false') . "\n";
echo "Match First & Last\n";
$Pattern = Pattern(_, 5, _);
echo "True? : ";
echo ($Pattern->matches(1,5,2) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches(1,1,5,2,2) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches(6,6,6) ? 'true' : 'false') . "\n";
echo "Match Multiple----\n";
$Pattern = Pattern(_, _, 5, _);
echo "True? : ";
echo ($Pattern->matches(1,1,5,2) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches(1,5,2) ? 'true' : 'false') . "\n";
echo "Match All (Set)---\n";
$Pattern = Pattern([_]);
echo "True? : ";
echo ($Pattern->matches(1,2,3,4,5,6) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches() ? 'true' : 'false') . "\n";
echo "Match Ending in 5\n";
$Pattern = Pattern([_], 5);
echo "True? : ";
echo ($Pattern->matches(1,1,1,5) ? 'true' : 'false') . "\n";
echo "True? : ";
echo ($Pattern->matches(5,5,5,5) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches(5) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches(1,1,1,1,5,1) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches(1,1,1,1,5,1) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches(1,1,1,1,5,1,1) ? 'true' : 'false') . "\n";
echo "Match Middle 5----\n";
$Pattern = Pattern([_], 5, [_]);
echo "True? : ";
echo ($Pattern->matches(1,2,3,5,3,2,1) ? 'true' : 'false') . "\n";
echo "True? : ";
echo ($Pattern->matches(9,5,9) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches(1,1,1,1,5) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches(5) ? 'true' : 'false') . "\n";
echo "Match second last-\n";
$Pattern = Pattern([_], 5, _);
echo "True? : ";
echo ($Pattern->matches(1,1,1,1,5,1) ? 'true' : 'false') . "\n";
echo "True? : ";
echo ($Pattern->matches(1,5,1) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches(5,1) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches(1,2,3,5) ? 'true' : 'false') . "\n";
echo "Match second------\n";
$Pattern = Pattern(_, 5, [_]);
echo "True? : ";
echo ($Pattern->matches(9,5,3) ? 'true' : 'false') . "\n";
echo "True? : ";
echo ($Pattern->matches(9,5,3,3,3) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches(5,1) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches(1,2,3,4,5) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches(4,5) ? 'true' : 'false') . "\n";
echo "Multiple Sets------\n";
$Pattern = Pattern([_], 1, 2, [_], 7, _, 9, [_]);
echo "True? : ";
echo ($Pattern->matches(0,1,2,3,4,5,6,7,8,9,10,11,12) ? 'true' : 'false') . "\n";
echo "True? : ";
echo ($Pattern->matches(0,1,1,1,1,1,2,3,4,5,6,7,8,9,10,11,12) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches(0,1,2,3,4,5,6,7,9,10,11,12) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches(1,2,3,4,5,6,7,8,9,10,11,12) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches(1,2,3,4,5,6,7,8,9) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches(0,1,2,7,8,9,0) ? 'true' : 'false') . "\n";
echo "False? : ";
echo ($Pattern->matches(1,2,7,8,9) ? 'true' : 'false') . "\n";